config/routes.rb
Brackets4life::Application.routes.draw do

  devise_for :users, :controllers => { :invitations => 'users/invitations', :sessions => "users/sessions", :registrations => "users/registrations" }


  # static pages
  root :to => 'static_pages#index'
  get '/about' => 'static_pages#about'
  get '/tournament' => 'static_pages#tournament'
  get '/prizes' => 'static_pages#prizes'
  get '/charities' => 'static_pages#charities'
  # resources
  resources :brackets # :except => [:edit, :update, :new]
  post '/brackets/new' => 'brackets#new', :as => "new_bracket"

  resources :donations, only: [:new, :create]

  resource :payments, only: [:new, :create]

end

app/models/bracket.rb
class Bracket < ActiveRecord::Base
	# dependencies
	require "bracket_math" # lib/bracket_math.rb

	# properties
	attr_accessible :name, :user, :score, :active

	# validations
	validates :name, :user, :presence => true

	# associations
	belongs_to :user
	has_many :predictions, :dependent => :destroy

	# helper methods for reaching through to the prediction scopes
	def region r
		self.predictions.region r
	end

	def slot m
		self.predictions.slot m
	end

	def round r
		self.predictions.round r
	end

	# Calculates the score of the bracket using the official standings
	#
	# Points are awarded as:
	# - The four play-in games prior to the first round will not be included
	# - All incorrect predictions will result in 0 points
	# - 1 for predicting a winner from round 1
	# - 2 for predicting a winner from round 2
	# - 4 for predicting a winner from the sweet sixteen
	# - 8 for predicting a winner from the elite eight
	# - 16 for predicting a winner from the final four
	# - 32 for predicting the winner of the championship game
	def update_score!
		score = 0
		predictions.each do |p|
			if p.correct?
				score += (2 ** p.round)
			end
		end
		self.update_attributes :score => score
	end

	def regions
		return BracketMath::BracketMathHelper.get_region_order
	end

	def slots(region, round)
		return BracketMath::BracketMathHelper.get_slots region, round
	end

	def winner_slot(slot)
		return BracketMath::BracketMathHelper.get_winner_slot slot
	end

	def final_four
		return BracketMath::BracketMathHelper.get_final_four_order
	end
end

app/controllers/brackets_controller.rb
class BracketsController < ApplicationController
	before_filter :authenticate_user!, except: [:edit, :update, :destroy, :show]
	before_filter :verify_bracket_user, only: [:edit, :update, :destroy, :show]


	def index
		# list all the brackets for the current user
		@brackets = current_user.brackets
		@referred = current_user.referred
		@unusedCreds = if @brackets.present? then [@referred - (@brackets.length * 3), 0].max else "all" end
		inactiveBrackets = []
		@brackets.each do |b|
			if (not b.active) 
				inactiveBrackets.push(b)
			end
		end

		bracketsToActivate = (@referred / 3.0).to_i - (@brackets.length - inactiveBrackets.length)
		for i in 0...bracketsToActivate
			if i < inactiveBrackets.length
				inactiveBrackets[i].active = true;
				inactiveBrackets[i].save!
			end
		end
		
		@referral_url = request.base_url + "/users/sign_up?ref=" + current_user.id.to_s

		respond_to do |format|
			format.html  # index.html.erb
			format.json  { render :json => @brackets }
		end
	end

	def new
		redirect_to root_path, :notice => "Sorry, Bracket creation has ended"
		# render a new bracket page

		# # redirect_to root_path, :notice => "The time period for creating a bracket has closed, but you can still donate!"
		# if current_user.brackets.length >= 3
		# 	redirect_to root_path, :notice => "Sorry, you can only create 3 brackets at a time!"
		# else
		# 	@bracket ||= Bracket.new params[:bracket]
		# 	@predictions = @bracket.predictions
		# 	return
		# end
	end

	def create
		redirect_to root_path, :notice => "Sorry, Bracket creation has ended"
		# require 'json'
		# @bracket = current_user.brackets.new(:name => params[:bracket][:name])
		
		# # parse the json part of the form to create prediction objects
		
		# predictions = JSON.parse params[:bracket][:predictions]
		# predictions.each_with_index do |winner_id, slot| 
		# 	@bracket.predictions << Prediction.new(:slot => slot, :winner_id => winner_id, :bracket => @bracket)
		# end

		# @bracket.save

		# if @bracket.predictions.length != 63
		# 	flash[:notice] = "Bracket was invalid! Please try again"
		# 	@bracket.destroy
		# 	redirect_to brackets_path
		# 	return
		# end
		
		# redirect_to new_payments_path(:bracket_id => @bracket.id)
	end

	def show

		@bracket = Bracket.find(params[:id])
		@predictions = @bracket.predictions.includes(:winner)
		if current_user.referred >= 3
			@bracket.update_score!
			@bracket.save!
		end	
	end

	def edit
		# render an edit page
	end

	def update
		# will update a users bracket
		@bracket = Bracket.find(params[:id])
		@bracket.update_score!
		@bracket.save!
	end

	def destroy
		Bracket.delete(params[:id])
		redirect_to brackets_path
	end


	private

	def verify_bracket_user
		authenticate_user!
		@bracket = Bracket.find(params[:id])
		if @bracket.user != current_user
			render nothing: true, status: :forbidden
		end
	end

end

app/helpers/brackets_helper.rb
module BracketsHelper
end

app/views/brackets/_brackets_table.html.erb
<table class="table table-bordered brackets-table">
	<tr>
		<th class="text-center">Name</th>
		<th class="text-center">Active?</th>
		<th class="text-center">Score</th>
		<th class="text-center">Controls</th>
	</tr>
	<% @brackets.each do |b| %>
	<tr>
		<td class="text-center">
			<%= link_to b.name, b %>
		</td>
		<td class="text-center">
			<% if b.active %>
			<i class="glyphicon glyphicon-ok"></i>
			<% else %>
			<%= link_to "activate now!", new_payments_path(:bracket_id => b.id) %>
			<% end %>
		</td>
		<td class="text-center">
			<%= b.score %>
		</td>
		<td class="text-center">
			<%= link_to bracket_path(b), :method => "delete", :confirm => "Are you sure you want to delete the bracket called #{b.name}? If you have already donated, we cannot issue a refund." do %>
			delete
			<% end %>
		</td>
	</tr>
	<% end %>
</table>

app/views/brackets/_formatted_bracket.html.erb
<% editable ||= false %>

<div class="bracket" data-editable="<%= editable %>">
	<div class="clearfix"></div>

	<% (0..3).each do |region_num| %>
		<div class="region" id="region<%= region_num %>" data-region="<%= @bracket.regions[region_num] %>">
			<%# The round0 slots are predetermined %>
			<ul class="round round0" data-region="<%= @bracket.regions[region_num] %>" data-round="0">
				<% @bracket.slots(region_num, 0).each do |slot| %>
					<li class="game" id="game<%= slot %>" data-winner-to="<%= slot %>">
						<ul class="teams">
							<% t = Team.slot(slot*2).first %>
							<li class="team team1" data-team-id="<%= t.id %>" data-starting-slot="<%= slot*2 %>">		
								<% if t != nil %>
									<span class="seed">
										<%= t.seed %>
									</span>
									<span class="team-name">
										<%= t.name %>
									</span>
								<% end %>
							</li>
							<% t = Team.slot(slot*2 + 1).first %>
							<li class="team team2" data-team-id="<%= t.id %>" data-starting-slot="<%= slot*2 + 1 %>">
								<% if t != nil %>
									<span class="seed">
										<%= t.seed %>
									</span>
									<span class="team-name">
										<%= t.name %>
									</span>
								<% end %>
							</li>
						</ul>
					</li>
				<% end %>
			</ul>
			<% (1..3).each do |round| %>
				<ul class="round round<%= round %>" data-region="<%= @bracket.regions[region_num] %>" data-round="<%= round %>">
					<% @bracket.slots(region_num, round-1).each_slice(2) do |slot1, slot2| %>
						<li class="game" id="game<%= @bracket.winner_slot(slot1) %>" data-winner-to="<%= @bracket.winner_slot(slot1) %>">
							<ul class="teams">
								<li class="team team1" id="winner-of-<%= slot1 %>" data-slot="<%= slot1 %>">
									<% p = @predictions.slot(slot1) %>
									<% t = p.any? ? p.first.winner : nil %>
									<span class="seed">
										<%= t.seed if t != nil %>
									</span>
									<span class="team-name" style="<%= if p.any? then 'color: ' + p.first.color end %>">
										<%= t.name if t != nil %>
									</span>
								</li>
								<li class="team team2" id="winner-of-<%= slot2 %>" data-slot="<%= slot2 %>">
									<% p = @predictions.slot(slot2) %>
									<% t = p.any? ? p.first.winner : nil %>
									<span class="seed">
										<%= t.seed if t != nil %>
									</span>
									<span class="team-name" style="<%= if p.any? then 'color: ' + p.first.color end %>">
										<%= t.name if t != nil %>
									</span>
								</li>
							</ul>
						</li>
					<% end %>
				</ul>
			<% end %>
			<ul class="round round4" data-region="<%= @bracket.regions[region_num] %>" data-round="4">
				<% slot = 56 + region_num %>
				<li class="region-winner">
					<div class="team" id="winner-of-<%= slot %>" data-slot="<%= slot%>" data-opponent-slot="<%= (slot % 2 == 0) ? slot+1 : slot-1 %>" data-winner-to="<%= (slot == 56 || slot == 57) ? 60 : 61 %>">
						<% p = @predictions.slot(slot) %>
						<% t = p.any? ? p.first.winner : nil %>
						<span class="seed">
							<%= t.seed if t != nil %>
						</span>
						<span class="team-name" style="<%= if p.any? then 'color: ' + p.first.color end %>">
							<%= t.name if t != nil %>
						</span>
					</div>
				</li>
			</ul>
		</div>
	<% end %> <%# end regions %>

	<div class="final-four">
		<div class="final-four-inner">
			<div class="final-four-one">
				<div class="team" id="winner-of-60" data-slot"60" data-opponent-slot="61" data-winner-to="62">
					<% p = @predictions.slot(60) %>
					<% t = p.any? ? p.first.winner : nil %>
					<span class="seed">
						<%= t.seed if t != nil %>
					</span>
					<span class="team-name" style="<%= if p.any? then 'color: ' + p.first.color end %>">
						<%= t.name if t != nil %>
					</span>
				</div>
			</div>
			<div class="final-four-two">
				<div class="team" id="winner-of-61" data-slot="61" data-opponent-slot="60" data-winner-to="62">
					<% p = @predictions.slot(61) %>
					<% t = p.any? ? p.first.winner : nil %>
					<span class="seed">
						<%= t.seed if t != nil %>
					</span>
					<span class="team-name" style="<%= if p.any? then 'color: ' + p.first.color end %>">
						<%= t.name if t != nil %>
					</span>
				</div>
			</div>
			<div class="champion">
				<div class="champion-inner">
					<div class="champion-image-container">
						<img alt="champion" class="champion-image" src="https://d21zi4m0jgpff8.cloudfront.net/trophy.png">
					</div>
					<div class="team" id="winner-of-62" data-slot="62">
						<% p = @predictions.slot(62) %>
						<% t = p.any? ? p.first.winner : nil %>
						<span class="seed">
							<%= t.seed if t != nil %>
						</span>
						<span class="team-name" style="<%= if p.any? then 'color: ' + p.first.color end %>">
							<%= t.name if t != nil %>
						</span>
					</div>
				</div>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
	<div class="clearfix"></div>

</div>

app/views/brackets/_new_bracket_modal.html.erb
<div class="modal fade" id="new-bracket" tabindex="-1" role="dialog" aria-labelledby="new-bracket-label" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="new-bracket-label">Name your New Bracket</h4>
			</div>
			<div class="modal-body">
				<%= semantic_form_for Bracket.new, :method => :post, :url => new_bracket_path do |f| %>
				<%= f.input :name, :required => false %>
				<%= f.action :submit, :button_html => {:class => "btn btn-primary"} %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/brackets/_sign_up_modal.html.erb
	<div class="modal fade" id="newUserModal" tabindex="-1" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="myModalLabel">New User</h4>
				</div>
				<h1 class="text-center">Sign up</h1>

				<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
				<%= devise_error_messages! %>

				<div class="form-field"><%= f.label :name %>
					<%= f.text_field :name, :autofocus => true, :required => true %></div>

					<div class="form-field"><%= f.label :email %>
						<%= f.email_field :email, :autofocus => true, :required => true %></div>

						<div class="form-field"><%= f.label :password %>
							<%= f.password_field :password, :class => "modal-form-input", :minlength => 8, :required => true %></div>

							<div class="form-field"><%= f.label :password_confirmation %>
								<%= f.password_field :password_confirmation, :class => "modal-form-input", :required => true %></div>

								<%= f.hidden_field :referral_code, value: -1 %>

								<div class="form-field"><%= f.label :charity %>
									<%= f.select(:charity, $charities) %></div>

									<div class="form-field"><%= f.submit "Sign up", :class => "cta btn btn-primary" %></div>
									<% end %>
									
								<!--div class="links text-center">
									<%= render "devise/shared/links" %>
								</div-->
							</div>
							<script>
								var password = $("#user_password.modal-form-input")[0]
								var confirm_password = $("#user_password_confirmation.modal-form-input")[0];

								function validatePassword(){
									if(password.value != confirm_password.value) {
										confirm_password.setCustomValidity("Passwords Don't Match");
									} else {
										confirm_password.setCustomValidity('');
									}
								}

								password.onchange = validatePassword;
								confirm_password.onkeyup = validatePassword;
								</script

app/views/brackets/index.html.erb
<section>
	<div class="container">
		<h1 class="text-center">Your Brackets</h1>

		<div class="row">
			<div class="col-sm text-center">
				<% if @brackets.present? %>
				<%= render "brackets_table" %>
				<% else %>
				<% end %>
			<!--button type="button" class="btn btn-primary btn-lg" style="margin-left: 5px" data-toggle="modal" data-target="#new-bracket">
				Create New Bracket
			</button-->
			Bracket creation is over, but you can still <%= link_to 'Donate!', new_donation_path, :class => "" %>
		</div>
		<!-- /.row -->
	</div>
		<h2 class="page-header">Your credits</h2>
		<div class "row">
			<h3 class="text-center">
			<strong>
			You currently have <%= @referred %> credits (<%= @unusedCreds %> remaining) 
			</strong>
			</h3>
			<h4 class="text-center">
				It takes 3 credits to activate a bracket. Here's how you get more:
			</h4>
			<br />
		</div>
		<div class="col-lg-6">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h2><strong><i class="glyphicon glyphicon-gift"></i> Donate $5<strong></h2>
				</div>
				<div class="panel-body text-center">
					<h1>$5 donation = 3 credits</h1>
					<br />
					<br />
					<br />
					<%= link_to 'Click Here to Donate', new_donation_path, :class => "btn btn-primary btn-lg" %>
					<br />
					<br />
					<br />
				</div>
			</div>
		</div>

		<div class="col-lg-6">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h2><strong><i class="glyphicon glyphicon-user"></i> Refer 3 Friends Who Sign Up<strong></h2>
				</div>
				<div class="panel-body text-center">
					<h1>1 referral = 1 credit</h1>		
					<p>
					Share this link now to invite your friends:
					<h3><%= link_to(@referral_url, @referral_url) %></h3>
					<div id="share_buttons"></div>
					<script>
						$('#share_buttons').share({
							networks: ['email', 'twitter','facebook','tumblr','pinterest','googleplus'],
							orientation: 'horizontal',
							urlToShare: "<%= @referral_url %>",
							title: "Join Brackets4Life!",
							pageDesc: "I just signed up for the Brackets 4 Life 2016 March Madness Tournament to help in the fight against SIDS! Join me:" 
						});
				</script>
					</p>
				</div>
			</div>
		</div>
	<%= render 'new_bracket_modal' %>
</section>

app/views/brackets/new.html.erb
<section>
	<div class="container">

	<h1 class="text-center">Choose your Winners</h1>
	<h2 class="text-center bracket-name">
		Bracket name: <%= @bracket.name %>
	</h2>

	<div class="text-center">
		<div class="btn-group bracket-buttons">
			<button type="button" class="btn btn-lg btn-default" data-target="bracket-undo">Undo</button>
			<button type="button" class="btn btn-lg btn-default" data-target="bracket-reset">Reset</button>
			<button type="button" class="btn btn-lg btn-default" data-target="bracket-randomize">Randomize</button>
		</div>
		&nbsp;&nbsp;
		<button type="button" class="btn btn-lg btn-primary" data-target="bracket-submit">Submit</button>
	</div>

	<div class="bracket-error-holder">
		<div class="bracket-error hidden text-center">
			<p>Please fill out the entire bracket!</p>
		</div>
	</div>
</div>

	<%= render "formatted_bracket", :editable => true %>

	<%= form_for @bracket, :id => "bracket-data" do |f| %>
	<%= f.hidden_field :name %>
	<%= f.hidden_field :predictions %>
	<% end %>
</section>

app/views/brackets/show.html.erb
<div class="container text-center">
	<h1><%= @bracket.name %></h1>
	<h2>Score: <%= @bracket.score %></h2>
</div>

<%= render "formatted_bracket", :editable => false %>