config/routes.rb
Brackets4life::Application.routes.draw do

  devise_for :users, :controllers => { :invitations => 'users/invitations', :sessions => "users/sessions", :registrations => "users/registrations" }


  # static pages
  root :to => 'static_pages#index'
  get '/about' => 'static_pages#about'
  get '/tournament' => 'static_pages#tournament'
  get '/prizes' => 'static_pages#prizes'
  get '/charities' => 'static_pages#charities'
  # resources
  resources :brackets # :except => [:edit, :update, :new]
  post '/brackets/new' => 'brackets#new', :as => "new_bracket"

  resources :donations, only: [:new, :create]

  resource :payments, only: [:new, :create]

end

app/views/shared/_alerts.html.erb
<div class="darker">
	<% if flash[:notice] %>
	<div class="container">
		<div class="alert alert-info">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<%= flash[:notice] %>
		</div>
	</div>
	<% end %>
	<% if flash[:alert] %>
	<div class="container">
		<div class="alert alert-warning">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<%= flash[:alert] %>
		</div>
	</div>
	<% end %>
</div>

app/views/shared/_footer.html.erb
<footer>
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<ul class="unstyled text-center">
					<li>
						<a href="https://www.facebook.com/brackets4life">
							<%= image_tag "media.png", :class => "facebook" %></a>
						<a href="https://twitter.com/brackets4life" class="twitter-follow-button" data-show-count="false">Follow @brackets4life</a>
					</li>
					<li> 
						Built by <a href="http://inthecube.org"> The Cube</a> &amp; Maintained by Arihant Jain &amp; Vishnu Menon
					</li>
					<li>
						Copyright &copy; 2016 Brackets4Life. All rights reserved
					</li>
				</ul>
			</div>
		</div>
	</div>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-content">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= image_tag "logo.svg", :class => "navbar-brand", :id => "navbar-logo" %>
      <%= link_to "Brackets4Life", root_path, :class => "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-content">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path%></li>
        <li><%= link_to "About Us", about_path%></li>
        <li><%= link_to "Tournament", tournament_path%></li>
        <li><%= link_to "Prizes", prizes_path%></li>
        <!-- <li><%= link_to "Charities", charities_path%></li> -->
        <li><a href="/users/sign_in"> Sign In </a></li>
        <% if user_signed_in? %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            My Account <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'My Brackets', brackets_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
        
        
        <% else %>
        <!--li><%= link_to "Get Started", new_user_registration_path %></li-->
         <li> <a class= "btn btn-primary btn-nav" href="" data-toggle="modal" data-target="#newUserModal">Get Started</a> </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>