config/routes.rb
Brackets4life::Application.routes.draw do

  devise_for :users, :controllers => { :invitations => 'users/invitations', :sessions => "users/sessions", :registrations => "users/registrations" }


  # static pages
  root :to => 'static_pages#index'
  get '/about' => 'static_pages#about'
  get '/tournament' => 'static_pages#tournament'
  get '/prizes' => 'static_pages#prizes'
  get '/charities' => 'static_pages#charities'
  # resources
  resources :brackets # :except => [:edit, :update, :new]
  post '/brackets/new' => 'brackets#new', :as => "new_bracket"

  resources :donations, only: [:new, :create]

  resource :payments, only: [:new, :create]

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

	def new
	end

	def create
	  # Amount in cents
	  @amt = params[:payment_amt]

	  if @amt.match(/\A[+-]?\d+?(\.\d+)?\Z/) == nil
	  	@amt = 500
	  else
	  	@amt = @amt.to_i
	  end

	  email = "anonymous@mail.com"

	  if current_user
	  	email = current_user.email if !current_user.email.blank?
	  end

	  begin
	  	customer = Stripe::Customer.create(
	  		:email => email,
	  		:card  => params[:stripeToken]
	  		)

	  	charge = Stripe::Charge.create(
	  		:customer    => customer.id,
	  		:amount      => @amt,
	  		:description => 'Bracket Customer',
	  		:currency    => 'usd'
	  		)

	  rescue Stripe::CardError => e
	  	flash[:error] = e.message
	  else
	  	current_user.referred += (@amt.to_i / 500).to_i * 3;
	  	current_user.paid = current_user.paid || 0
	  	current_user.paid += @amt.to_i;
      	current_user.save!
	  end


	  flash[:success] = "Thank You for your contribution!"
	  redirect_to '/brackets'

	end
end

app/views/donations/create.html.erb
<section>
	<div class="container">
		<div class="bracket-payment-message">
			<div class="row">
				<div class="col-xs-12">
					<p class="text-center lead">Thank you! You donated <strong>$<%= (@amt.to_i / 100) %>.00</strong> to fight SIDS!</p>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/donations/new.html.erb
<section class="text-center">
	<div class="container">
			<div class="col-xs-12">
				<h1>Thank you for supporting SIDS Research!</h1>
				<p class="lead">Every donation will bring us one step closer to finding a cure for Sudden Infant Death Syndrome.</p>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12">
				<form class="donation-form">
					<label>Amount</label>
					<select class="opts_donate">
						<option value="5">$5</option>
						<option value="10">$10</option>
						<option value="20">$20</option>
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="500">$500</option>
						<option value="1000">$1,000</option>
						<option value="5000">$5,000</option>
					</select>
				</form>
				<%= form_tag donations_path do %>
				<input id="stripe_token" name="stripeToken" type="hidden" value="" />
				<input id="payment_amt" name="payment_amt" type="hidden" value="500" />
				<article>
					<label class="amount">
						Total
						<span id="amt_shown">$5.00</span>
					</label>
				</article>
				<a href="" class="btn btn-primary hero-btn" id="donateButton">Donate</a>
				<% end %> 
			</div>
		</div>
	</div>
</section>