config/routes.rb
Brackets4life::Application.routes.draw do

  devise_for :users, :controllers => { :invitations => 'users/invitations', :sessions => "users/sessions", :registrations => "users/registrations" }


  # static pages
  root :to => 'static_pages#index'
  get '/about' => 'static_pages#about'
  get '/tournament' => 'static_pages#tournament'
  get '/prizes' => 'static_pages#prizes'
  get '/charities' => 'static_pages#charities'
  # resources
  resources :brackets # :except => [:edit, :update, :new]
  post '/brackets/new' => 'brackets#new', :as => "new_bracket"

  resources :donations, only: [:new, :create]

  resource :payments, only: [:new, :create]

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  before_filter :authenticate_user!

  def new
    @bracket = Bracket.find(params[:bracket_id])
    @referral_url = request.base_url + "/users/sign_up?ref=" + current_user.id.to_s
    @referred = current_user.referred
  end

  def create
    @bracket = Bracket.find(params[:bracket_id])

    # Amount in cents
    @amt = params[:payment_amt]

    if @amt.match(/\A[+-]?\d+?(\.\d+)?\Z/) == nil
      @amt = 500
    else
      @amt = @amt.to_i
    end

    begin
      customer = Stripe::Customer.create(
       :email => current_user.email,
       :card  => params[:stripeToken]
       )

      charge = Stripe::Charge.create(
       :customer    => customer.id,
       :amount      => @amt,
       :description => 'Bracket Customer',
       :currency    => 'usd'
       )
    rescue Stripe::CardError => e
      flash[:error] = e.message
    else
      current_user.referred += (@amt.to_i / 500).to_i * 3;
      current_user.paid = current_user.paid || 0
      current_user.paid += @amt.to_i;
      current_user.save!
      @bracket.active = true
      @bracket.save!
    end

    flash[:alert] = "Thank You for your contribution!"
    redirect_to '/brackets'

  end


end

app/views/payments/create.html.erb
<section>
	<div class="container">
		<div class="bracket-payment-message">
			<div class="row">
				<div class="col-xs-12">
					<p class="text-center lead">Thank you! You donated <strong>$<%= (@amt.to_i / 100) %>.00</strong>!</p>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/payments/new.html.erb
<section class="text-center">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<h1>Thank you for supporting SIDS Research!</h1>
				<p class="lead">Now that you've created a bracket, it's time to donate! In order to activate your bracket, you must donate a minimum of $5. Every donation will bring us one step closer to finding a cure for Sudden Infant Death Syndrome.</p>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12">
				<form class="donation-form">
					<label>Additional Amount</label>
					<select class="opts">
						<option value="0" selected="selected">$0</option>
						<option value="5">$5</option>
						<option value="10">$10</option>
						<option value="15">$10</option>
						<option value="20">$20</option>
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="500">$500</option>
						<option value="1000">$1,000</option>
						<option value="5000">$5,000</option>
					</select>
				</form>
				<%= form_tag payments_path do %>
				<input id="stripe_token" name="stripeToken" type="hidden" value="" />
				<input id="payment_amt" name="payment_amt" type="hidden" value="500" />
				<input id="bracket_id" name="bracket_id" type="hidden" value="<%= @bracket.id %>" />
				<article>
					<label class="amount">
						Total
						<span id="amt_shown">$5.00</span>
					</label>
				</article>
				<a href="/payments/create" class="btn btn-primary hero-btn" id="paymentButton">Donate</a>
				<% end %> 
				<br />
				<h5>Or, invite 3 people instead! So far, you have <%= @referred %> credits. Each successful referral gets you one more. Here's your link: </h5>
				<h3><%= link_to(@referral_url, @referral_url) %></h3>
				<div id="share_buttons"></div>
				<script>
					$('#share_buttons').share({
						networks: ['email', 'twitter','facebook','tumblr','pinterest','googleplus'],
						orientation: 'horizontal',
						urlToShare: "<%= @referral_url %>",
						pageDesc: "I just signed up for the Brackets 4 Life 2016 March Madness Tournament to help in the fight against SIDS! Join me:" 
					});

				</script>
			</div>
		</div>
	</div>
</section>